#pragma once

#define BS_SYMBOL_CARET_DOWN_FILL "\xef\x88\xa9"
#define BS_SYMBOL_COLLECTION "\xef\x8b\x8c"
#define BS_SYMBOL_CONTROLLER "\xef\x8b\x94"
#define BS_SYMBOL_DISPLAY "\xef\x8c\x82"
#define BS_SYMBOL_GEAR_FILL "\xef\x8f\xa2"
#define BS_SYMBOL_PLAY_BTN "\xef\x93\xb1"
#define BS_SYMBOL_PLAY_CIRCLE_FILL "\xef\x93\xb2"
#define BS_SYMBOL_POWER "\xef\x93\xbf"
#define BS_SYMBOL_QUESTION_CIRCLE_FILL "\xef\x94\x84"
#define BS_SYMBOL_TV "\xef\x97\xad"
#define BS_SYMBOL_X_LG "\xef\x99\x99"
#define BS_SYMBOL_APPLE "\xef\x99\x9b"
#define BS_SYMBOL_WINDOWS "\xef\x99\x9e"
#define BS_SYMBOL_STEAM "\xef\x9b\x81"
#define BS_SYMBOL_WINDOW_DESKTOP "\xef\x9b\x8e"
